server:
  ip: 127.0.0.1
  port: 8877

log:
  log_path: ./logs
  log_name: log.log

mysql:
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  db: chat

redis:
  host: 127.0.0.1
  port: 6379